spring.application.name=newspring

#spring.mvc.apiversion.use.header=API-Version

# Global, applies to all groups
#spring.http.client.service.read-timeout=2s
#spring.http.client.service.group.randomnumbergenerator.base-url=http://localhost:8081